"""refactor_jobs_module

Revision ID: 007977c7f7e9
Revises: 55d004e75a94
Create Date: 2026-01-18 17:47:40.836378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '007977c7f7e9'
down_revision: Union[str, None] = '55d004e75a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_applications_job_id_fkey', 'job_applications', type_='foreignkey')
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('format', sa.Enum('ONSITE', 'REMOTE', 'HYBRID', name='jobformat'), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT', name='jobemploymenttype'), nullable=False),
    sa.Column('required_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'CLOSED', 'REJECTED', name='jobstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_application_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('job_postings')
    op.drop_index('ix_ai_chat_messages_created_at', table_name='ai_chat_messages')
    op.drop_index('ix_conversation_participants_user_id', table_name='conversation_participants')
    op.drop_constraint('event_materials_event_id_fkey', 'event_materials', type_='foreignkey')
    op.create_foreign_key(None, 'event_materials', 'events', ['event_id'], ['id'])
    op.drop_constraint('event_messages_event_id_fkey', 'event_messages', type_='foreignkey')
    op.create_foreign_key(None, 'event_messages', 'events', ['event_id'], ['id'])
    op.drop_constraint('event_reviews_event_id_fkey', 'event_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'event_reviews', 'events', ['event_id'], ['id'])
    op.drop_constraint('event_speakers_event_id_fkey', 'event_speakers', type_='foreignkey')
    op.create_foreign_key(None, 'event_speakers', 'events', ['event_id'], ['id'])
    op.drop_column('events', 'max_attendees')
    op.drop_column('events', 'date_time')
    op.add_column('job_applications', sa.Column('applied_at', sa.DateTime(), nullable=False))
    op.alter_column('job_applications', 'resume_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # Moved to top

    op.create_foreign_key(None, 'job_applications', 'jobs', ['job_id'], ['id'])
    op.drop_column('job_applications', 'created_at')
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.add_column('users', sa.Column('system_roles', sa.ARRAY(sa.String()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'system_roles')
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'])
    op.add_column('job_applications', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.create_foreign_key('job_applications_job_id_fkey', 'job_applications', 'job_postings', ['job_id'], ['id'])
    op.alter_column('job_applications', 'resume_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('job_applications', 'applied_at')
    op.add_column('events', sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('max_attendees', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event_speakers', type_='foreignkey')
    op.create_foreign_key('event_speakers_event_id_fkey', 'event_speakers', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'event_reviews', type_='foreignkey')
    op.create_foreign_key('event_reviews_event_id_fkey', 'event_reviews', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'event_messages', type_='foreignkey')
    op.create_foreign_key('event_messages_event_id_fkey', 'event_messages', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'event_materials', type_='foreignkey')
    op.create_foreign_key('event_materials_event_id_fkey', 'event_materials', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_conversation_participants_user_id', 'conversation_participants', ['user_id'], unique=False)
    op.create_index('ix_ai_chat_messages_created_at', 'ai_chat_messages', ['created_at'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('job_type', postgresql.ENUM('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT', name='jobtype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('salary_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('posted_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], name='job_postings_posted_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='job_postings_pkey')
    )
    op.drop_table('job_chat_messages')
    op.drop_table('jobs')
    # ### end Alembic commands ###
