"""add_headline

Revision ID: 1d42908b91dd
Revises: 9d669eb5fdbf
Create Date: 2025-12-12 04:58:11.424854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d42908b91dd'
down_revision: Union[str, None] = '9d669eb5fdbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('headline', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'headline')
    # ### end Alembic commands ###
