"""Add mentorship request

Revision ID: dad61c1fd886
Revises: 17349a5313a7
Create Date: 2025-12-06 10:27:27.527013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dad61c1fd886'
down_revision: Union[str, None] = '17349a5313a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new enum type
    new_enum = sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='mentorshipstatus')
    new_enum.create(op.get_bind())

    op.add_column('mentorship_requests', sa.Column('sender_id', sa.UUID(), nullable=False))
    op.add_column('mentorship_requests', sa.Column('receiver_id', sa.UUID(), nullable=False))
    op.add_column('mentorship_requests', sa.Column('message', sa.Text(), nullable=True))
    op.alter_column('mentorship_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', name='mentorshiprequeststatus'),
               type_=new_enum,
               existing_nullable=False,
               postgresql_using='status::text::mentorshipstatus')
    op.drop_constraint('mentorship_requests_mentor_id_fkey', 'mentorship_requests', type_='foreignkey')
    op.drop_constraint('mentorship_requests_mentee_id_fkey', 'mentorship_requests', type_='foreignkey')
    op.create_foreign_key(None, 'mentorship_requests', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'mentorship_requests', 'users', ['receiver_id'], ['id'])
    op.drop_column('mentorship_requests', 'mentee_id')
    op.drop_column('mentorship_requests', 'intro_message')
    op.drop_column('mentorship_requests', 'goals')
    op.drop_column('mentorship_requests', 'mentor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorship_requests', sa.Column('mentor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('mentorship_requests', sa.Column('goals', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_requests', sa.Column('intro_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_requests', sa.Column('mentee_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mentorship_requests', type_='foreignkey')
    op.drop_constraint(None, 'mentorship_requests', type_='foreignkey')
    op.create_foreign_key('mentorship_requests_mentee_id_fkey', 'mentorship_requests', 'users', ['mentee_id'], ['id'])
    op.create_foreign_key('mentorship_requests_mentor_id_fkey', 'mentorship_requests', 'users', ['mentor_id'], ['id'])
    op.alter_column('mentorship_requests', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='mentorshipstatus'),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', name='mentorshiprequeststatus'),
               existing_nullable=False)
    op.drop_column('mentorship_requests', 'message')
    op.drop_column('mentorship_requests', 'receiver_id')
    op.drop_column('mentorship_requests', 'sender_id')
    # ### end Alembic commands ###
